#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 29 16:33:40 2018

@author: makoto
"""

cube = 27.0
epsilon = 0.01
guess = 0.0
increment = 0.0001

num = 0

while abs(guess**3 - cube) >= epsilon and guess <= cube:
    guess += increment
    num += 1
print('num is', num)
if abs(guess**3 - cube) >= epsilon:
    print('failed')
else:
    print(guess, 'is an approximate solution')