#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  2 18:04:39 2018

@author: makoto
"""

cube = float(input('Enter a number: '))
abscube = abs(cube)
epsilon = 0.0000000001
num = 0
low = 0
if abscube >= 1:
    high = abscube
elif 0 <abscube and abscube < 1:
    high = 1
guess = (high + low)/2.0
while abs(guess**3 - abscube) >= epsilon:
    if guess**3 < abscube:
        low = guess
    else:
        high = guess
    guess = (high + low)/2.0
    num += 1
print('num =', num)
if cube < 0:
    guess = -guess
print('guess =', guess)
