#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  2 18:04:39 2018

@author: makoto
"""

cube = 0.05
epsilon = 0.0000000001
num = 0
low = 0
high = 1
guess = (high + low)/2.0
while abs(guess**3 - cube) >= epsilon:
    if guess**3 < cube:
        low = guess
    else:
        high = guess
    guess = (high + low)/2.0
    num += 1
print('num =', num)
print('guess =', guess)
