#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 29 23:41:47 2018

@author: makoto
"""

x = 25
epsilon = 0.01
step = 0.001
guess = 1.0
num = 0

while guess <= x:
    if abs(guess**2 -x) < epsilon:
        break
    else:
        guess += step
        num += 1

if abs(guess**2 - x) >= epsilon:
    print('failed')
else:
    print('succeeded: ' + str(guess))